### ISSUE TITLE
How to set date field format?

### ISSUE THREAD

**Issue by mtancek** [Jocoon/php-parquet#3]
Hi,

how can be set date field format? Is it possible?

**Comment by emrecanmuslu** [comment]
`
$dateTimeField = new DataColumn(
            DataField::createFromType('dateTime', DateTimeImmutable::class),
           [ new DateTimeImmutable('now') ]
        );
`

**Comment by emrecanmuslu** [comment]
```php
$dateTimeField = new DataColumn(
            DataField::createFromType('datetime', DateTimeImmutable::class),
           [ new DateTimeImmutable('now') ]
        );
```
Hi,
You can use it this way.

**Comment by mtancek** [comment]
Hi,

thanks. It's working.
