### ISSUE TITLE
Predicate pushdown / filtering

### ISSUE THREAD

**Issue by rmarlow** [Jocoon/php-parquet#7]
Is predicate pushdown available in this library? That is, can I specify criteria beyond which fields I want to read? After examining the README and source code, it appears that this is not supported. Are there plans to add this feature?

**Comment by KevinVonJocoon** [comment]
This library is intended as a 'low-level' library for interacting with parquet files. Predicate pushdown is a feature of processing/analytical frameworks like Spark, Hadoop (in a broader sense), Apache Drill, etc. and not part of this project.
Nonetheless, usually the DataColumnStatistics and other data (e.g. dictionaries) can be used for performing evaluations on which row groups to read/skip to reduce the amount of raw data you have to read.

This means, if the software you've been using for generating a parquet file (including this project) wrote correct statistics data, you can evaluate it before reading the DataColumn itself and thereby, skip row groups that don't include your requested data (in a conclusive manner) - e.g. if you're searching for an integer column for a value `123` and your column/page only contains `min: 3` and `max: 50`, it is obvious you can skip reading this part. This filtering might be more complex for other datatypes.

At the moment, there is no simplified/comfortable way to do this in a super-simple-1-liner, but I'll incorporate your thoughts in the further development of the library. From my perspective, it would be nice to have an abstraction layer/wrapper, that allows filtering for specific criteria during raw-read-time. I'd refrain from including this in the core classes responsible for reading the data, as we still have to do helpers/utilities that ease the use of the data, e.g. something similar to the table-abstractions in parquet-dotnet.

**Comment by rmarlow** [comment]
Thank you so much for the thorough and considerate response. I'll consider this in our design, and I look forward to your future development on this project.
